; Neutral mapping from already-ratified my-lisp semantic identities
; to target ABI mechanism imports. This file does not define Lisp meaning.
((kind . wsm-target-operation-table)
 (schema . "wsm-target-operation-table-v1")
 (version . 1)
 (target-contract . ((schema . "wsm-os-target-v1") (version . 6)))
 (semantic-authority . ((repository . "juv4uk/my-lisp")
                        (commit . "e206294301e5c98b1b4d3cd536989faee4205b59")
                        (path . "lib/surface/semantic-registry.lisp")))
 (operations .
  (((canonical-id . "0002")
    (target-operation . wsm_atom)
    (representation-effect . classify-target-value-shape)
    (authority-owner . my-lisp)
    (status . ratified)
    (consumers . (cml wsm-os-lisp))
    (witness . "wsm-os-target::RUNTIME_IMPORTS"))
   ((canonical-id . "0003")
    (target-operation . wsm_eq)
    (representation-effect . compare-target-values)
    (authority-owner . my-lisp)
    (status . ratified)
    (consumers . (cml wsm-os-lisp))
    (witness . "wsm-os-target::RUNTIME_IMPORTS"))
   ((canonical-id . "0004")
    (target-operation . wsm_cons)
    (representation-effect . allocate-cons-cell)
    (authority-owner . my-lisp)
    (status . ratified)
    (consumers . (cml wsm-os-lisp))
    (witness . "wsm-os-target::RUNTIME_IMPORTS"))
   ((canonical-id . "0005")
    (target-operation . wsm_car)
    (representation-effect . read-cons-car)
    (authority-owner . my-lisp)
    (status . ratified)
    (consumers . (cml wsm-os-lisp))
    (witness . "wsm-os-target::RUNTIME_IMPORTS"))
   ((canonical-id . "0006")
    (target-operation . wsm_cdr)
    (representation-effect . read-cons-cdr)
    (authority-owner . my-lisp)
    (status . ratified)
    (consumers . (cml wsm-os-lisp))
    (witness . "wsm-os-target::RUNTIME_IMPORTS"))))
 (unmapped-target-import-policy . fail-closed-no-semantic-id-inference))
